# .goreleaser.yml
dist: dist
before:
  hooks:
    - go mod download
    - go generate ./...
    - go mod tidy

builds:
  - id: dns-to-route-resolver
    binary: dns-to-route-resolver
    main: ./cmd/dns-to-route-resolver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    tags:
      - netgo

archives:
  - id: dns-to-route-resolver
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^refactor:'
      - '^style:'
      - '^perf:'
      - '^build:'
      - '^wip:'
      - '^merge:'
      - '^bump:'
      - '^update:'
      - '^fix typo'